name: 🚀 Deploy & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  # 🏷️ Создание релиза
  create-release:
    name: 🏷️ Создание релиза
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: 📥 Checkout кода
      uses: actions/checkout@v4
      
    - name: 🏷️ Создание релиза
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## 🚀 Новый релиз ${{ github.ref_name }}
          
          ### ✨ Новые возможности:
          - WB API v2 с встроенной фильтрацией
          - Ozon API исправления
          - Комплексная система тестирования
          - Улучшенное логирование
          - GitHub Actions CI/CD
          
          ### 🔧 Исправления:
          - Удален дублирующий WB API v1
          - Оптимизирована производительность
          - Улучшена обработка ошибок
          
          ### 📚 Документация:
          - Полная инструкция по развертыванию
          - Руководство по тестированию
          - API документация
          
          ### 🧪 Тестирование:
          - 95+ unit тестов
          - Security тесты
          - Performance тесты
          - API compliance тесты
          
          **📥 Скачать:** [Архив с кодом](https://github.com/${{ github.repository }}/archive/${{ github.ref_name }}.zip)
        draft: false
        prerelease: false

  # 📦 Создание архива
  create-archive:
    name: 📦 Создание архива
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: 📥 Checkout кода
      uses: actions/checkout@v4
      
    - name: 📦 Создание архива
      run: |
        echo "📦 Создание архива для релиза..."
        
        # Создаем директорию для архива
        mkdir -p release-package
        
        # Копируем основные файлы
        echo "📁 Копирование основных файлов..."
        cp *.gs release-package/ 2>/dev/null || true
        cp *.html release-package/ 2>/dev/null || true
        cp *.md release-package/ 2>/dev/null || true
        
        # Создаем архив
        echo "🗜️ Создание ZIP архива..."
        cd release-package
        zip -r ../mp-review-manager-${{ github.ref_name }}.zip .
        cd ..
        
        # Показываем содержимое архива
        echo "📋 Содержимое архива:"
        unzip -l mp-review-manager-${{ github.ref_name }}.zip
        
        # Загружаем архив как артефакт
        echo "📤 Загрузка архива как артефакт..."
        
    - name: 📤 Загрузка архива
      uses: actions/upload-artifact@v3
      with:
        name: mp-review-manager-${{ github.ref_name }}
        path: mp-review-manager-${{ github.ref_name }}.zip

  # 🔍 Проверка готовности к развертыванию
  deployment-check:
    name: 🔍 Проверка готовности
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout кода
      uses: actions/checkout@v4
      
    - name: 🔍 Проверка готовности к развертыванию
      run: |
        echo "🔍 Проверка готовности к развертыванию..."
        
        # Проверяем наличие всех необходимых файлов
        echo "📁 Проверка файлов:"
        required_files=(
          "code.gs"
          "ozon_functions.gs"
          "tests.gs"
          "test_functions.gs"
          "comprehensive_tests.gs"
          "api_fixes_implementation.gs"
          "wb_v2_only_tests.gs"
          "wb_api_comparison_test.gs"
          "StoreManagerSidebar.html"
          "README_GITHUB.md"
          "DEPLOYMENT_GUIDE.md"
          "API_DOCUMENTATION_ANALYSIS.md"
        )
        
        missing_files=()
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "  ✅ $file"
          else
            echo "  ❌ $file - ОТСУТСТВУЕТ"
            missing_files+=("$file")
          fi
        done
        
        if [ ${#missing_files[@]} -gt 0 ]; then
          echo "❌ Отсутствуют файлы: ${missing_files[*]}"
          exit 1
        fi
        
        # Проверяем размер файлов
        echo "📊 Проверка размера файлов:"
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            size=$(wc -c < "$file")
            if [ $size -gt 100 ]; then
              echo "  ✅ $file - $size байт"
            else
              echo "  ⚠️ $file - $size байт (мало)"
            fi
          fi
        done
        
        # Проверяем синтаксис основных файлов
        echo "🔧 Проверка синтаксиса:"
        for file in *.gs; do
          if [ -f "$file" ]; then
            if grep -q "function " "$file"; then
              echo "  ✅ $file - содержит функции"
            else
              echo "  ⚠️ $file - не содержит функций"
            fi
          fi
        done
        
        echo "🎉 Проверка готовности завершена успешно!"

  # 📊 Генерация отчета о развертывании
  deployment-report:
    name: 📊 Отчет о развертывании
    runs-on: ubuntu-latest
    needs: [create-release, create-archive, deployment-check]
    if: always()
    
    steps:
    - name: 📊 Генерация отчета
      run: |
        echo "📊 ===== ОТЧЕТ О РАЗВЕРТЫВАНИИ ====="
        echo ""
        echo "🏷️ Создание релиза: ${{ needs.create-release.result }}"
        echo "📦 Создание архива: ${{ needs.create-archive.result }}"
        echo "🔍 Проверка готовности: ${{ needs.deployment-check.result }}"
        echo ""
        
        if [ "${{ needs.create-release.result }}" = "success" ] && 
           [ "${{ needs.create-archive.result }}" = "success" ] && 
           [ "${{ needs.deployment-check.result }}" = "success" ]; then
          echo "🎉 РАЗВЕРТЫВАНИЕ УСПЕШНО ЗАВЕРШЕНО!"
          echo "✅ Релиз создан"
          echo "✅ Архив готов"
          echo "✅ Система готова к использованию"
          exit 0
        else
          echo "❌ ОШИБКИ ПРИ РАЗВЕРТЫВАНИИ"
          echo "🔧 Проверьте логи выше"
          exit 1
        fi
        
        echo ""
        echo "📚 Следующие шаги:"
        echo "1. Скачайте архив релиза"
        echo "2. Следуйте инструкции в DEPLOYMENT_GUIDE.md"
        echo "3. Настройте Google Apps Script"
        echo "4. Загрузите файлы в проект"
        echo "5. Настройте API ключи"
        echo "6. Запустите тесты"
        echo ""
        echo "📊 ===== КОНЕЦ ОТЧЕТА ====="