name: 📊 Monitoring & Health Check

on:
  schedule:
    # Проверка каждый час
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  # 🔍 Проверка здоровья репозитория
  repository-health:
    name: 🔍 Здоровье репозитория
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout кода
      uses: actions/checkout@v4
      
    - name: 🔍 Проверка здоровья репозитория
      run: |
        echo "🔍 Проверка здоровья репозитория..."
        
        # Проверяем размер репозитория
        echo "📊 Размер репозитория:"
        du -sh . | awk '{print "  📁 Общий размер: " $1}'
        
        # Проверяем количество файлов
        file_count=$(find . -type f | wc -l)
        echo "  📄 Количество файлов: $file_count"
        
        # Проверяем количество строк кода
        code_lines=$(find . -name "*.gs" -o -name "*.js" -o -name "*.html" | xargs wc -l | tail -1 | awk '{print $1}')
        echo "  📝 Строк кода: $code_lines"
        
        # Проверяем количество функций
        function_count=$(grep -r "function " *.gs 2>/dev/null | wc -l)
        echo "  🔧 Функций: $function_count"
        
        # Проверяем количество тестов
        test_count=$(grep -r "function test" *.gs 2>/dev/null | wc -l)
        echo "  🧪 Тестов: $test_count"
        
        # Проверяем документацию
        doc_count=$(find . -name "*.md" | wc -l)
        echo "  📚 Документов: $doc_count"

  # 📈 Анализ активности
  activity-analysis:
    name: 📈 Анализ активности
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout кода
      uses: actions/checkout@v4
      
    - name: 📈 Анализ активности
      run: |
        echo "📈 Анализ активности..."
        
        # Анализ коммитов
        echo "📊 Статистика коммитов:"
        git log --oneline --since="1 week ago" | wc -l | awk '{print "  📅 За неделю: " $1 " коммитов"}'
        git log --oneline --since="1 month ago" | wc -l | awk '{print "  📅 За месяц: " $1 " коммитов"}'
        
        # Анализ изменений
        echo "📊 Статистика изменений:"
        git log --since="1 week ago" --pretty=format: --name-only | sort | uniq -c | sort -rn | head -10 | while read count file; do
          echo "  📄 $file: $count изменений"
        done
        
        # Анализ авторов
        echo "📊 Статистика авторов:"
        git log --since="1 month ago" --pretty=format:"%an" | sort | uniq -c | sort -rn | while read count author; do
          echo "  👤 $author: $count коммитов"
        done

  # 🧪 Проверка тестов
  test-health:
    name: 🧪 Здоровье тестов
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout кода
      uses: actions/checkout@v4
      
    - name: 🧪 Проверка здоровья тестов
      run: |
        echo "🧪 Проверка здоровья тестов..."
        
        # Подсчитываем тесты
        echo "📊 Статистика тестов:"
        
        # Unit тесты
        unit_tests=$(grep -r "function test" tests.gs 2>/dev/null | wc -l)
        echo "  🧪 Unit тесты: $unit_tests"
        
        # WB API тесты
        wb_tests=$(grep -r "function test" wb_v2_only_tests.gs 2>/dev/null | wc -l)
        echo "  🛒 WB API тесты: $wb_tests"
        
        # Comprehensive тесты
        comp_tests=$(grep -r "function test" comprehensive_tests.gs 2>/dev/null | wc -l)
        echo "  🔬 Comprehensive тесты: $comp_tests"
        
        # Общее количество тестов
        total_tests=$((unit_tests + wb_tests + comp_tests))
        echo "  📊 Всего тестов: $total_tests"
        
        # Проверяем покрытие
        echo "📊 Покрытие тестами:"
        if [ $total_tests -gt 50 ]; then
          echo "  ✅ Отличное покрытие ($total_tests тестов)"
        elif [ $total_tests -gt 20 ]; then
          echo "  ⚠️ Хорошее покрытие ($total_tests тестов)"
        else
          echo "  ❌ Низкое покрытие ($total_tests тестов)"
        fi

  # 📚 Проверка документации
  documentation-health:
    name: 📚 Здоровье документации
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout кода
      uses: actions/checkout@v4
      
    - name: 📚 Проверка здоровья документации
      run: |
        echo "📚 Проверка здоровья документации..."
        
        # Проверяем основные документы
        echo "📊 Статистика документации:"
        
        docs=(
          "README_GITHUB.md:README"
          "DEPLOYMENT_GUIDE.md:Руководство по развертыванию"
          "API_DOCUMENTATION_ANALYSIS.md:Анализ API"
          "GITHUB_COMMIT_INSTRUCTIONS.md:Инструкции по коммитам"
        )
        
        for doc_info in "${docs[@]}"; do
          file=$(echo $doc_info | cut -d: -f1)
          name=$(echo $doc_info | cut -d: -f2)
          
          if [ -f "$file" ]; then
            size=$(wc -c < "$file")
            lines=$(wc -l < "$file")
            echo "  ✅ $name: $size байт, $lines строк"
          else
            echo "  ❌ $name: ОТСУТСТВУЕТ"
          fi
        done
        
        # Проверяем качество README
        if [ -f "README_GITHUB.md" ]; then
          echo "📖 Качество README:"
          
          if grep -q "## Описание" "README_GITHUB.md"; then
            echo "  ✅ Содержит описание"
          else
            echo "  ❌ Не содержит описание"
          fi
          
          if grep -q "## Установка" "README_GITHUB.md"; then
            echo "  ✅ Содержит инструкции по установке"
          else
            echo "  ❌ Не содержит инструкции по установке"
          fi
          
          if grep -q "## Использование" "README_GITHUB.md"; then
            echo "  ✅ Содержит примеры использования"
          else
            echo "  ❌ Не содержит примеры использования"
          fi
        fi

  # 🎯 Итоговый отчет мониторинга
  monitoring-report:
    name: 🎯 Отчет мониторинга
    runs-on: ubuntu-latest
    needs: [repository-health, activity-analysis, test-health, documentation-health]
    if: always()
    
    steps:
    - name: 🎯 Генерация отчета мониторинга
      run: |
        echo "🎯 ===== ОТЧЕТ МОНИТОРИНГА ====="
        echo "📅 Дата: $(date)"
        echo "🕐 Время: $(date +%H:%M:%S)"
        echo ""
        
        echo "📊 Статус проверок:"
        echo "  🔍 Здоровье репозитория: ${{ needs.repository-health.result }}"
        echo "  📈 Анализ активности: ${{ needs.activity-analysis.result }}"
        echo "  🧪 Здоровье тестов: ${{ needs.test-health.result }}"
        echo "  📚 Здоровье документации: ${{ needs.documentation-health.result }}"
        echo ""
        
        # Подсчет успешных проверок
        success_count=0
        total_count=4
        
        if [ "${{ needs.repository-health.result }}" = "success" ]; then
          ((success_count++))
        fi
        
        if [ "${{ needs.activity-analysis.result }}" = "success" ]; then
          ((success_count++))
        fi
        
        if [ "${{ needs.test-health.result }}" = "success" ]; then
          ((success_count++))
        fi
        
        if [ "${{ needs.documentation-health.result }}" = "success" ]; then
          ((success_count++))
        fi
        
        success_rate=$((success_count * 100 / total_count))
        
        echo "📈 Общий статус: $success_rate%"
        echo ""
        
        if [ $success_rate -eq 100 ]; then
          echo "🎉 ВСЕ ПРОВЕРКИ ПРОЙДЕНЫ УСПЕШНО!"
          echo "✅ Система в отличном состоянии"
          exit 0
        elif [ $success_rate -ge 75 ]; then
          echo "⚠️ Большинство проверок пройдено"
          echo "🔧 Требуется внимание к $((total_count - success_count)) компонентам"
          exit 0
        else
          echo "❌ Критические проблемы обнаружены"
          echo "🚨 Требуется немедленное вмешательство"
          exit 1
        fi
        
        echo ""
        echo "🎯 ===== КОНЕЦ ОТЧЕТА ====="